[package]
name = "gcf_alloc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gcf_bb = { path = "../gcf_bb" }
smallvec = { version = "1.10.0", features = ["union"] }
